### ISSUE TITLE
Cannot enter master pin

### ISSUE THREAD

**Issue by 21heisca** [Dazzozo/mkey#2]
I put down the date on my 3ds into the generator, and put in the service inquiry. The generator then gives me a master key that is 5 digits long. The problem with this is that when I try to type it in, there is only enough space to type in 4 digits. I cannot enter the master key because there is not enough space. Is there a 4 digit master key?
  
Never mind, I had no idea that I had to click "ok" to actually enter the master key. XD

**Comment by momoneyzay** [comment]
Gfgfgg
